### ISSUE TITLE
Scaling stroke widths

### ISSUE THREAD

**Issue by KnutSv** [morlay/svg-scaler#1]
Is there any way of scaling stroke widths when scaling a svg?

**Comment by morlay** [comment]
Nope. have to outline stroke to paths first before scale. 
There are a tool working in processing for it https://github.com/morlay/outline-stroke.

**Comment by KnutSv** [comment]
Thanks, that looks really cool. What's the ETA?

**Comment by morlay** [comment]
Not sure，I have another important things to do first.
That tool could work for outlining stroke now,
![image](https://cloud.githubusercontent.com/assets/1667873/21839583/7862ccac-d813-11e6-9946-6923ee976b24.png)
https://github.com/morlay/outline-stroke/tree/master/examples

But I think we should find some method to join paths. 
And the `miterlimit` should support too.

So prefer use Inkscape or Illustrator or Sketch to process them first.

**Comment by KnutSv** [comment]
Ok, guess I'll outline them manually for now then. Thanks again :)
